# Generated by Django 3.0.8 on 2020-07-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la secretaría')),
            ],
            options={
                'verbose_name': 'Secretaría',
                'verbose_name_plural': 'Secretarías',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=100, verbose_name='ID de Contrato')),
                ('year', models.PositiveIntegerField(verbose_name='Año de la obra')),
                ('contract_object', models.TextField(max_length=900, verbose_name='Objeto del contrato')),
                ('total_value', models.FloatField(verbose_name='Valor total')),
                ('progress_work', models.PositiveIntegerField(verbose_name='% de Avance de la Obra')),
                ('pqr', models.TextField(max_length=900, verbose_name='Petición, Queja o Reclamo')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='WorkState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de un estado de un contrato')),
            ],
            options={
                'verbose_name': 'Estado de la obra',
                'verbose_name_plural': 'Estados de las obras',
            },
        ),
        migrations.CreateModel(
            name='WorkCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Work', verbose_name='Obra a la que pertenece')),
            ],
            options={
                'verbose_name': 'Coordenada de la obra',
                'verbose_name_plural': 'Coordenadas de las obras',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='actual_work_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.WorkState', verbose_name='Estado actual'),
        ),
        migrations.AddField(
            model_name='work',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Secretary', verbose_name='Secretaría Responsable'),
        ),
    ]
