# Generated by Django 3.0.8 on 2020-07-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcoordinate',
            name='name',
            field=models.CharField(default='Coordenadas de la obra', max_length=100, verbose_name='Nombre'),
        ),
    ]
