# Generated by Django 3.0.8 on 2020-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200716_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='total_value',
            field=models.CharField(max_length=100, verbose_name='Valor total'),
        ),
    ]
