# Generated by Django 3.0.8 on 2020-07-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200716_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Email de la secretaría'),
            preserve_default=False,
        ),
    ]
