# Generated by Django 3.0.8 on 2020-07-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_secretary_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery/works/', verbose_name='Imágen')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Work', verbose_name='Obra a la que pertenece')),
            ],
            options={
                'verbose_name': 'Imágen de la obra',
                'verbose_name_plural': 'Imagenes de las obras',
            },
        ),
    ]
