# Generated by Django 3.0.8 on 2020-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='icon',
            field=models.ImageField(default=1, upload_to='uploads/marker_icons/secretary/', verbose_name='Icono de la secretaría'),
            preserve_default=False,
        ),
    ]
