# Generated by Django 3.0.8 on 2021-05-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unico_rotulo', models.CharField(max_length=100, unique=True, verbose_name='Numero unico del rotulo')),
                ('latitude_desde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud desde (coordenada)')),
                ('longitude_desde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud desde (coordenada)')),
                ('latitude_hasta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud hasta (coordenada)')),
                ('longitude_hasta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud hasta (coordenada)')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('exclusivo_compartido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exclusivo/Compartido')),
                ('cajas_inspeccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cajas de inspección')),
                ('ducterias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ducterias')),
                ('tipo_zona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de zona')),
                ('costo_unidad_constructiva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo de la unidad constructiva')),
            ],
            options={
                'verbose_name': 'Camara y Canalización',
                'verbose_name_plural': 'Camaras y Canalizaciones',
            },
        ),
        migrations.CreateModel(
            name='Luminaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unico_rotulo', models.CharField(max_length=100, unique=True, verbose_name='Numero unico del rotulo')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitud (coordenada)')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitud (coordenada)')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('tipo_fuente_luminica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de fuente Luminica')),
                ('potencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Potencia')),
                ('tipo_luminaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de luminaria')),
                ('tipo_balastro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de balastro')),
                ('valor_perdidas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor de las perdidas')),
                ('control_encendido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Control de encendido')),
                ('tipo_espacio_luminado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de espacio luminado')),
                ('identificacion_transformador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificación del transformador de distribución')),
                ('medidor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medidor')),
                ('nivel_tension', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel de tensión')),
                ('horas_diarias_funcionamiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horas diaras de funcionamiento')),
                ('costo_unidad_constructiva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo de la unidad constructiva')),
            ],
            options={
                'verbose_name': 'Luminaria',
                'verbose_name_plural': 'Luminarias',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unico_rotulo', models.CharField(max_length=100, unique=True, verbose_name='Numero unico del rotulo')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitud (coordenada)')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitud (coordenada)')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('exclusivo_compartido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exclusivo/Compartido')),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de material')),
                ('longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('costo_unidad_constructiva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo de la unidad constructiva')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unico_rotulo', models.CharField(max_length=100, unique=True, verbose_name='Numero unico del rotulo')),
                ('latitude_desde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud desde (coordenada)')),
                ('longitude_desde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud desde (coordenada)')),
                ('latitude_hasta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud hasta (coordenada)')),
                ('longitude_hasta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud hasta (coordenada)')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('exclusivo_compartido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exclusivo/Compartido')),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de material')),
                ('calibre_conductores', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calibre de conductores')),
                ('tipo_instalacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de instalación')),
                ('costo_unidad_constructiva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo de la unidad constructiva')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
        migrations.CreateModel(
            name='Transformador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unico_rotulo', models.CharField(max_length=100, unique=True, verbose_name='Numero unico del rotulo')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitud (coordenada)')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitud (coordenada)')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('exclusivo_compartido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exclusivo/Compartido')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('capacidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad')),
                ('valor_catastral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor catastral del terreno')),
                ('area_terreno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area del terreno')),
                ('costo_unidad_constructiva', models.CharField(blank=True, max_length=100, null=True, verbose_name='Costo de la unidad constructiva')),
            ],
            options={
                'verbose_name': 'Transformador',
                'verbose_name_plural': 'Transformadores',
            },
        ),
    ]
