# Generated by Django 3.0.8 on 2021-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_lighting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='num_unico_rotulo',
            field=models.CharField(max_length=100, verbose_name='Numero unico del rotulo'),
        ),
        migrations.AlterField(
            model_name='luminaria',
            name='num_unico_rotulo',
            field=models.CharField(max_length=100, verbose_name='Numero unico del rotulo'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='num_unico_rotulo',
            field=models.CharField(max_length=100, verbose_name='Numero unico del rotulo'),
        ),
        migrations.AlterField(
            model_name='red',
            name='num_unico_rotulo',
            field=models.CharField(max_length=100, verbose_name='Numero unico del rotulo'),
        ),
        migrations.AlterField(
            model_name='transformador',
            name='num_unico_rotulo',
            field=models.CharField(max_length=100, verbose_name='Numero unico del rotulo'),
        ),
    ]
